// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iflfyzofdcpabxowwxnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmbGZ5em9mZGNwYWJ4b3d3eG5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTM0NzEsImV4cCI6MjA2OTYyOTQ3MX0.pmndFRD66PUWaYKVzEODHLugzhaFwoDOvchdxPZ2evY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});